services:
  - type: web
    name: biasharatrack-backend
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: PORT
        value: 10000
      - key: DB_USER
        value: vinomondi
      - key: DB_PASSWORD
        value: biasharatrack
      - key: DB_ENDPOINT
        value: biashara-trackdb.clwwxo0qhvvw.us-east-1.rds.amazonaws.com
      - key: DB_NAME
        value: biashara-trackdb
      - key: DB_PORT
        value: 3306
      - key: MPESA_CONSUMER_KEY
        value: 9VNZwhHV8GnJMYAmHWRVffjZVlReury443CpxiH5KA7WENne
      - key: MPESA_CONSUMER_SECRET
        value: VwAUMo6PA3nZEoX2O9iHbLOulrRrmm8gTumLce1puOoBQ6xgksc41rstOT2NJbwu
      - key: MPESA_PASSKEY
        value: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
      - key: MPESA_BUSINESS_SHORTCODE
        value: 174379
      - key: MPESA_ENVIRONMENT
        value: sandbox
      - key: JWT_SECRET
        value: CENTOMEN

  - type: static
    name: biasharatrack-frontend
    buildCommand: cd frontened && npm install && npm run build
    publishDir: frontened/dist
    envVars:
      - key: VITE_API_URL
        value: https://biasharatrack-backend.onrender.com